Meteor.subscribe("fen");
Meteor.subscribe("theProfiles");
Meteor.subscribe("theSaves");
Meteor.subscribe("userData");
Meteor.subscribe("matchings");
Meteor.subscribe("games");
Meteor.subscribe("thePieces");
Meteor.subscribe("theThemeOfPiece");
Meteor.subscribe("thePersonalTheme");